### PR TITLE
Install the header files

### PR DESCRIPTION
**Pull request by leitao**
When installing a shared library, the header file needs to be installed. This
is a patch that enables the installation and uninstallation of the .h headers.

### CODE REVIEW

**Comment by tuliom** [comment]
I don't understand why this is necessary.
libvecpf works by extending printf via its own callback hooks for specialized data types.  You don't need to have access to new symbols' definitions at build time in order to use it. You only need access to altivec.h and stdio.h, which aren't provided by this library.
So, the question is: why do you need to install this header?

**Comment by leitao** [comment]
Good question. I had the concept that all libraries should have an external .h file to describe the functions that is going to be exported. It seems to not be true, right?

**Comment by tuliom** [comment]
@leitao You're right.
In most cases, libraries export new symbols (variables, functions, etc.) which require a header file describing its API.
In this particular case, it extends an available API through its own hooks.  So, libvecp doesn't export any new symbol.

**Comment by leitao** [comment]
Thanks Tulio!

**Pull request closed without merging**
